config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'sales#index'

  resources :sales do
    collection do
      post :import
    end
  end

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sale.rb
# frozen_string_literal: true

class Sale < ApplicationRecord
  require 'csv'
  validates :customer_name, presence: true
  validates :item_description, presence: true
  validates :item_price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :merchant_name, presence: true
  validates :merchant_address, presence: true

  class << self
    def import(file)
      CSV.foreach(file.path, encoding: 'UTF-8', headers: true, header_converters: :symbol, converters: :all) do |row|
        Sale.create! row.to_hash
      end
    end

    def total_sales_revenue!
      total = 0
      Sale.all.each do |sale|
        raise unless sale.valid?

        total += sale.item_price * sale.quantity
      end
      total
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :remember_token

  before_save { email.downcase! }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # Returns the hash digest of the given string.
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns the hash digest of the given string.
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  before_action :authenticate_user!

  private

  def authenticate_user!
    unless logged_in?
      redirect_to login_url, flash: { danger: 'Please login to continue' }
    end
  end
end

app/controllers/sales_controller.rb
# frozen_string_literal: true

class SalesController < ApplicationController
  def index
    @sales = Sale.all
    begin
      @revenue = Sale.total_sales_revenue!
    rescue StandardError => e
      Rails.logger.error "could not calculate revenue: #{e}"
      @revenue = -1
    end
  end

  def import
    if params[:file]
      begin
        Sale.import(params[:file])
        redirect_to root_url, flash: { success: 'CSV Imported' }
      rescue
        redirect_to root_url, flash: { danger: 'Unable to process CSV file.' }
      end
    else
      redirect_to root_url, flash: { danger: 'No file given. Select a CSV file.' }
    end
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  skip_before_action :authenticate_user!

  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      log_in user
      redirect_to root_url
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to login_url, flash: { success: 'Logged out' }
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = 'Sales Admin'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user&.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="container">
  <%= link_to "The Company", root_path, id: "logo" %>
  <nav>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Sales", root_path %></li>
      <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Account <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to "Log out", logout_path, method: :delete %>
            </li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Log in", login_path %></li>
      <% end %>
    </ul>
  </nav>
</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/sales/index.html.erb
<h1>Update Sales Figures</h1>

<div>
    <%= form_tag import_sales_path, multipart: true do %>
      <span class="btn btn-default">
        <%= file_field_tag :file %>
      </span>
      <%= submit_tag "Upload", class:"btn btn-primary" %>
    <% end %> 
</div>

<h1>Current Sales Figures</h1>

<div class="alert alert-info">
  <strong>
    Total Sales Revenue: <%= if @revenue >= 0 then number_to_currency @revenue else 'Unavailable' end   %>
  </strong>
</div>

<table class="table table-striped table-hover">
  <thead>
    <th>Customer Name</th>
    <th>Item</th>
    <th>Price</th>
    <th>Quantity</th>
    <th>Merchant Name</th>
    <th>Merchant Address</th>
  </thead>
  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.customer_name %></td>
        <td><%= sale.item_description %></td>
        <td><%= number_to_currency sale.item_price %></td>
        <td><%= sale.quantity %></td>
        <td><%= sale.merchant_name %></td>
        <td><%= sale.merchant_address %></td>
      </tr>
    <% end %>
  </tbody>
</table>